name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: python3 ./.github/workflows/build.py --only-install-dependencies --os ${{ matrix.os }}

    - name: Compile
      run: python3 ./.github/workflows/build.py --only-compile --os ${{ matrix.os }}

